version: "3.9"

services:
    nginx:
        image: nginx
        working_dir: /var/www/html
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-net
        depends_on:
            - fpm
        ports:
            - '8098:80'

    fpm:
        build: ./docker
        volumes:
            - ./:/var/www/html
        networks:
            - app-net
        depends_on:
            - composer
            - postgres

    composer:
        image: composer:2.1.9
        volumes:
            - ./:/app
        networks:
            - app-net
        command: install --ignore-platform-reqs --no-interaction --no-plugins --no-scripts --prefer-dist
        working_dir: /app

    postgres:
        image: postgres:12.7
        restart: always
        environment:
            POSTGRES_DB: socnet
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: GDhdyGiJhwu8
        volumes:
            - ./.database:/var/lib/postgresql/data
        networks:
            - app-net
        ports:
            - '5440:5432'

    redis:
        image: bitnami/redis:7.0.5
        restart: always
        environment:
            REDIS_PASSWORD: JkEi7R8d2EDi
        volumes:
            - ./.redis:/bitnami/redis/data
        networks:
            - app-net
        ports:
            - '6379:6379'

networks:
    app-net:
        driver: bridge
