version: "3.9"

services:
    nginx:
        image: nginx
        ports:
            - 8098:80
        working_dir: /var/www/html
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - fpm
        links:
            - fpm

    fpm:
        build: ./docker
        volumes:
            - ./:/var/www/html
        depends_on:
            - composer
            - postgres

    composer:
        image: composer:2.1.9
        volumes:
            - ./:/app
        command: install --ignore-platform-reqs --no-interaction --no-plugins --no-scripts --prefer-dist
        working_dir: /app

    postgres:
        image: postgres:12.7
        restart: always
        environment:
            POSTGRES_DB: socnet
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: GDhdyGiJhwu8
        ports:
            - 5440:5432
